[[headers]]
for = "/*" # Apply to all files
[headers.values]
Cache-Control = "public, max-age=31536000, immutable" # Cache for 1 year

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "no-cache" # Prevent caching for the main HTML file
